<?php

/**
 * @file
 * Contains main module functions.
 */

/**
 * Implements hook_theme().
 */
function link_iframe_formatter_theme() {
  return [
    'link_iframe_formatter' => [
      'variables' => [
        'url' => NULL,
        'width' => NULL,
        'height' => NULL,
        'min_width' => NULL,
        'max_width' => NULL,
        'min_height' => NULL,
        'max_height' => NULL,
        'class' => NULL,
        'original' => NULL,
        'path' => NULL,
        'scrolling' => 'yes',
      ],
      'template' => 'link-iframe-formatter',
    ],
  ];

}
